[package]
name = "rust"
version = "0.1.0"
authors = ["Josef Vonasek <j.f.vonasek@gmail.com>"]
edition = "2018"

[lib]
crate_type = ["cdylib"]

[dependencies]
jni         = "0.17.0"
typed-arena = "2.0.1"
flatbuffers = "0.6.1"